### ISSUE TITLE
confusing on image format, entrypoint definition and parameter passing in X64.

### ISSUE THREAD

**Issue by jyao1** [universalpayload/documentation#18]
Current 0.75 spec uses definition below:
1) image format is ELF.

2) Entrypoint is cdecl
typedef
VOID
(__cdecl *PAYLOAD_ENTRY) (
  EFI_HOB_HANDOFF_INFO_TABLE *HobList
);

3) Parameter passing is RCX.
RCX holds the address of the HOB list for the 64bit payload.

Only if we use VS to build PE image, with _cdecl convention, the parameter is RCX.
However, if we use GCC to build ELF image, with _cdecl convention, the parameter is RDI, not RCX.
If we use GCC and we want RCX, we need use __attribute__((ms_abi)), instead of _cdecl.

**Comment by gdong1** [comment]
Thanks for the comments. The patch was merged.
