### ISSUE TITLE
Need clear term for payload, payload data

### ISSUE THREAD

**Issue by niruiyu** [universalpayload/documentation#8]
Today the spec uses "Image" for payload and uses "actual payload" for the payload data.
It's a bit confusing.
I suggest:
1. Use "Payload" for the entire image including payload header and the data
2. Use "Payload Data" for the data portion, excluding the payloader header, reloc header, auth header.

Field name in payload header can be changed accordingly.

**Comment by gdong1** [comment]
I agree with this change if current image format (adding a new header) is used.
But now we are trending to use ELF instead of adding a new image header.
So we might remove the image header section later one ELF image format is finalized.

**Comment by gdong1** [comment]
Spec was updated to version 0.75 in which ELF image format was used. so these terms are removed.
